### ISSUE TITLE
Feature Request: Add support for referning $User.Id

### ISSUE THREAD

**Issue by isidle** [rahulmalhotra/Platform-Event-Toast-LWC#2]
This one would be great for notifying the user of something, independent of the page they had open (e.g. "New Lead assigned").

**Comment by rahulmalhotra** [comment]
Hi @isidle can you specify a detailed use case for this? Currently you can make an announcement by running Platform Event Toast in system mode.

**Comment by rahulmalhotra** [comment]
Closing this issue as it's been over 30 days without any activity.
