### ISSUE TITLE
Is this compatible to SF release ICU Locale Format

### ISSUE THREAD

**Issue by DivyaGoelSF** [rahulmalhotra/Platform-Event-Toast-LWC#4]
Hello Rahul,

I have installed this component and would like to know if this is compatible to the Salesforce Winter release feature ICU Local Format.?

Thanks,
Divya

**Comment by rahulmalhotra** [comment]
Hi Divya, I think it shouldn't be affected by that change as we're setting up the toast messages ourselves while using the toast. Let me know if you've any further queries. Thanks!
