### ISSUE TITLE
Doesn't work in sandbox

### ISSUE THREAD

**Issue by pford1** [rahulmalhotra/Platform-Event-Toast-LWC#7]
I have this set up in Process Builder and Flow to create a "Toast Event" but the message doesn't appear.

Here's a screenshot of my process builder showing how I entered the info

![Screen Shot 2023-01-13 at 2 07 02 PM](https://user-images.githubusercontent.com/19935087/212428258-f307cd23-2692-4daa-a015-befbf5dacfc0.png)

And a screenshot of the record page w/ the Toast Event component

![Screen Shot 2023-01-13 at 2 07 34 PM](https://user-images.githubusercontent.com/19935087/212428262-adcb299a-f55b-432e-b89c-41abb4d1c159.png)

I had the process builder also update another field when fired so I could make sure it was firing, and it does, so that's not the issue

**Comment by rahulmalhotra** [comment]
Hi @pford1 where is the component embedded? Also, can you create a recording of all the components of the process builder + how you've setup toast on the page and share it's link? I can then have a look and maybe suggest a fix.

**Comment by pford1** [comment]
I just tried to recreate the problem and it now works. I must have done something strange. Thank you so much for this!
